<?php declare(strict_types=1);
namespace VO\Installer;
use Throwable; use VO\Database\MigrationRunner; use VO\Database\PdoConnection;
final class InstallerController
{
    private Template $tpl; private InstallerSession $session; private InstalledConfig $lock; private RequirementsChecker $req; private string $mig;
    public function __construct(private string $root)
    { $cfg=getenv('VO_INSTALLED_CONFIG_PATH') ?: $root.'/api/config/installed.php'; $storage=getenv('VO_STORAGE_PATH') ?: $root.'/api/storage'; $this->tpl=new Template(); $this->session=new InstallerSession(); $this->lock=new InstalledConfig($cfg); $this->req=new RequirementsChecker(dirname($cfg), $storage, $this->lock); $this->mig=$root.'/api/database/migrations'; }
    public function handle(): void
    {
        if ($this->lock->isInstalled()) $this->out('locked', [], 410);
        $this->session->start(); $step=$_GET['step'] ?? 'requirements';
        if ($_SERVER['REQUEST_METHOD']==='POST' && !$this->session->valid($_POST['csrf'] ?? null)) $this->out('error', ['message'=>'La solicitud venció. Volvé a intentar.'], 419);
        try { match($step){ 'requirements'=>$this->requirements(), 'database'=>$this->database(), 'details'=>$this->details(), 'review'=>$this->review(), 'run'=>$this->run(), default=>$this->out('requirements', $this->base()) }; } catch (Throwable) { $this->session->clearSecrets(); $this->out('error', ['message'=>'No se pudo completar la instalación. Revisá los datos y volvé a intentar.'], 500); }
    }
    private function base(array $x=[]): array { return $x + ['csrf'=>$this->session->csrf(), 'requirements'=>$this->req->check()]; }
    private function requirements(): void { if ($_SERVER['REQUEST_METHOD']==='POST') { if (!$this->req->passes()) $this->out('requirements', $this->base(['blocked'=>true]), 400); header('Location: ?step=database'); exit; } $this->out('requirements', $this->base()); }
    private function database(): void { if (!$this->req->passes()) $this->out('requirements', $this->base(['blocked'=>true]), 400); if ($_SERVER['REQUEST_METHOD']==='POST') { $db=$this->dbInput(); try { (new PdoConnection($db['dsn'],$db['user'],$db['password']))->select('SELECT 1'); $this->session->set('db',$db); header('Location: ?step=details'); exit; } catch (Throwable) { $this->session->clearSecrets(); $this->out('database', $this->base(['error'=>'No se pudo conectar a la base de datos.']), 400); } } $this->out('database', $this->base()); }
    private function details(): void { if (!$this->req->passes()) $this->out('requirements', $this->base(['blocked'=>true]), 400); if (!$this->session->get('db')) $this->out('database', $this->base(), 400); if ($_SERVER['REQUEST_METHOD']==='POST') { $data=$this->dataInput(); $err=$this->validate($data); if ($err) $this->out('details', $this->base(['error'=>$err,'data'=>$data]), 400); $this->session->set('data',$data); header('Location: ?step=review'); exit; } $this->out('details', $this->base(['data'=>$this->session->get('data', [])])); }
    private function review(): void { if (!$this->req->passes()) $this->out('requirements', $this->base(['blocked'=>true]), 400); if (!$this->session->get('db') || !$this->session->get('data')) $this->out('database', $this->base(), 400); $this->out('review', $this->base(['data'=>$this->session->get('data')])); }
    private function run(): void { if (!$this->req->passes()) $this->out('requirements', $this->base(['blocked'=>true]), 400); $db=$this->session->get('db'); $data=$this->session->get('data'); if (!$db || !$data) $this->out('database',$this->base(),400); $conn=new PdoConnection($db['dsn'],$db['user'],$db['password']); (new MigrationRunner($conn,$this->mig))->run(); if (getenv('VO_INSTALLER_FAIL_AFTER_MIGRATIONS')) throw new \RuntimeException('forced'); (new InstallerSeeder($conn))->seed($data); $this->lock->write($db, true); $this->session->destroy(); $this->out('done', [], 200); }
    private function dbInput(): array { $host=trim($_POST['host'] ?? '127.0.0.1'); $port=trim($_POST['port'] ?? '3306'); $name=trim($_POST['name'] ?? ''); return ['dsn'=>"mysql:host=$host;port=$port;dbname=$name;charset=utf8mb4", 'user'=>trim($_POST['user'] ?? ''), 'password'=>(string)($_POST['password'] ?? '')]; }
    private function dataInput(): array { return ['business_name'=>trim($_POST['business_name']??''),'business_slug'=>strtolower(preg_replace('/[^a-z0-9]+/','-',trim($_POST['business_name']??''))),'branch_name'=>trim($_POST['branch_name']??''),'branch_address'=>trim($_POST['branch_address']??''),'branch_phone'=>trim($_POST['branch_phone']??''),'timezone'=>'America/Argentina/Buenos_Aires','admin_name'=>trim($_POST['admin_name']??'Administrador'),'admin_email'=>trim($_POST['admin_email']??''),'admin_password'=>(string)($_POST['admin_password']??''),'admin_password_confirm'=>(string)($_POST['admin_password_confirm']??'')]; }
    private function validate(array $d): ?string { if ($d['business_name']===''||$d['branch_name']==='') return 'Completá comercio y sucursal.'; if (!filter_var($d['admin_email'], FILTER_VALIDATE_EMAIL)) return 'El email no es válido.'; if (strlen($d['admin_password'])<10 || !preg_match('/[A-Za-z]/',$d['admin_password']) || !preg_match('/\d/',$d['admin_password'])) return 'La contraseña debe tener 10 caracteres, letras y números.'; if ($d['admin_password']!==$d['admin_password_confirm']) return 'Las contraseñas no coinciden.'; return null; }
    private function out(string $view, array $data=[], int $status=200): never { http_response_code($status); echo $this->tpl->render($view, $data); exit; }
}
