<?php declare(strict_types=1);
namespace Tests;

use PDO; use Throwable; use VO\Database\MigrationRunner; use VO\Database\PdoConnection; use VO\Installer\InstallerSeeder;

final class AdminOrdersHttpTest extends TestCase
{
    public function testOrdersListDetailGuardAuditAndReadOnlyUi(): void
    {
        $s = AdminOrdersScratchDatabase::create(); [$h] = $this->harness($s);
        try { $ids = $s->seedOrder(); $this->login($h); $list = $h->request('GET','/admin/pedidos'); $this->assertSame(200,$list['status']); foreach (['Pedidos','B-000001','Pendiente','Centro','$ 10,00'] as $n) $this->assertTrue(str_contains($list['body'],$n),$n); $this->assertTrue(!str_contains($list['body'],'Aceptar') && !str_contains($list['body'],'Rechazar'));
            $filtered = $h->request('GET','/admin/pedidos?status=accepted'); $this->assertSame(200,$filtered['status']); $this->assertTrue(!str_contains($filtered['body'],'B-000001'));
            $detail = $h->request('GET','/admin/pedidos/' . $ids['order']); $this->assertSame(200,$detail['status']); foreach (['Ada','Burger','Cheese','Main 123','Descuentos','Movimientos de stock','reserve'] as $n) $this->assertTrue(str_contains($detail['body'],$n),$n); $this->assertSame(3,(int)$s->pdo->query("SELECT COUNT(*) FROM audit_log WHERE action IN ('orders.view_list','orders.view_detail') AND request_id IS NOT NULL")->fetchColumn());
            $s->pdo->exec("DELETE rp FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE p.permission_key='products.manage'"); $deny=$h->request('GET','/admin/pedidos'); $this->assertSame(403,$deny['status']); $this->assertSame(1,(int)$s->pdo->query("SELECT COUNT(*) FROM audit_log WHERE action='authz.denied'")->fetchColumn());
        } finally { $h->stop(); $s->drop(); }
    }
    private function harness(AdminOrdersScratchDatabase $s): array { $dir=$this->tempDir('admin_orders'); $lock=$dir.'/installed.php'; $s->install($lock); $h=new \InstallerTestServer(dirname(__DIR__).'/public_html',['VO_INSTALLED_CONFIG_PATH'=>$lock,'VO_STORAGE_PATH'=>$dir.'/storage','VO_HTTP_NO_REDIRECTS'=>'1']); $h->start(); return [$h,$lock]; }
    private function login(\InstallerTestServer $h): void { $r=$h->request('GET','/admin/login'); if (!preg_match('/name="csrf" value="([^"]+)"/',$r['body'],$m)) throw new \RuntimeException('Missing CSRF.'); $this->assertSame(302,$h->request('POST','/admin/login',['csrf'=>$m[1],'email'=>'owner@example.test','password'=>'Password123'])['status']); }
}

final class AdminOrdersScratchDatabase
{
    private function __construct(public string $name, public PDO $pdo, private PDO $server) {}
    public static function create(): self { try { $server=new PDO('mysql:host=127.0.0.1;port=3306;charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]); } catch (Throwable $e) { throw new \RuntimeException('MariaDB is REQUIRED for AdminOrdersHttpTest.',0,$e); } $name='vo_orders7_test_'.bin2hex(random_bytes(5)); $server->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"); $pdo=new PDO("mysql:host=127.0.0.1;port=3306;dbname=$name;charset=utf8mb4",'root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); return new self($name,$pdo,$server); }
    public function install(string $lock): void { $db=new PdoConnection("mysql:host=127.0.0.1;port=3306;dbname=$this->name;charset=utf8mb4",'root',''); (new MigrationRunner($db, dirname(__DIR__).'/api/database/migrations'))->run(); (new InstallerSeeder($db))->seed(['business_name'=>'Demo','business_slug'=>'demo','branch_name'=>'Centro','timezone'=>'America/Argentina/Buenos_Aires','admin_name'=>'Owner','admin_email'=>'owner@example.test','admin_password'=>'Password123']); if (!is_dir(dirname($lock))) mkdir(dirname($lock),0777,true); file_put_contents($lock,'<?php return '.var_export(['database'=>['dsn'=>"mysql:host=127.0.0.1;port=3306;dbname=$this->name;charset=utf8mb4",'user'=>'root','password'=>'']],true).';'); }
    public function seedOrder(): array { $branch=(int)$this->pdo->query('SELECT id FROM branches LIMIT 1')->fetchColumn(); $this->pdo->exec("INSERT INTO categories (name,slug) VALUES ('Food','food')"); $this->pdo->exec("INSERT INTO catalog_items (category_id,type,name,slug,base_price_cents,is_active) VALUES (1,'product','Burger','burger',1000,1)"); $item=(int)$this->pdo->lastInsertId(); $this->pdo->exec("INSERT INTO modifiers (group_id,name,price_delta_cents,is_active) SELECT id,'Cheese',100,1 FROM modifier_groups LIMIT 1"); if ((int)$this->pdo->query('SELECT COUNT(*) FROM modifiers')->fetchColumn()===0) { $this->pdo->exec("INSERT INTO modifier_groups (name,is_active) VALUES ('Toppings',1)"); $this->pdo->exec("INSERT INTO modifiers (group_id,name,price_delta_cents,is_active) VALUES ((SELECT id FROM modifier_groups LIMIT 1),'Cheese',100,1)"); } $mod=(int)$this->pdo->query('SELECT id FROM modifiers LIMIT 1')->fetchColumn(); $this->pdo->exec("INSERT INTO orders (business_id,branch_id,number,status,public_token,fulfillment,customer_name,customer_email,customer_phone,gross_items_cents,item_promotions_cents,order_promotions_cents,coupon_discount_cents,payment_discount_cents,merchandise_total_cents,delivery_fee_cents,grand_total_cents) VALUES (1,$branch,'B-000001','pending',REPEAT('a',64),'delivery','Ada','ada@test','555',1000,0,0,0,0,1000,0,1000)"); $order=(int)$this->pdo->lastInsertId(); $this->pdo->exec("INSERT INTO order_items (order_id,branch_id,item_id,item_name,quantity,unit_price_cents,modifiers_total_cents,gross_unit_cents,gross_line_cents,line_total_cents) VALUES ($order,$branch,$item,'Burger',1,1000,0,1000,1000,1000)"); $oi=(int)$this->pdo->lastInsertId(); $this->pdo->exec("INSERT INTO order_item_modifiers (order_item_id,modifier_id,group_name,modifier_name,price_delta_cents,qty) VALUES ($oi,$mod,'Toppings','Cheese',100,1)"); $this->pdo->exec("INSERT INTO order_addresses (order_id,type,recipient_name,phone,street,city) VALUES ($order,'delivery','Ada','555','Main 123','CABA')"); $this->pdo->exec("INSERT INTO order_discounts (order_id,kind,type,scope,amount_cents) VALUES ($order,'promotion','min_amount_pct','order',100)"); $this->pdo->exec("INSERT INTO stock_movements (business_id,branch_id,order_id,item_id,quantity_delta,reason) VALUES (1,$branch,$order,$item,1,'reserve')"); return ['order'=>$order]; }
    public function drop(): void { $this->server->exec("DROP DATABASE IF EXISTS `$this->name`"); }
}
