<?php declare(strict_types=1);
namespace Tests;

use PDO; use VO\Cart\CartRepository; use VO\Cart\CartService; use VO\Database\MigrationRunner; use VO\Domain\DbIdempotencyStore; use VO\Orders\OrderRepository; use VO\Orders\OrderService; use VO\Pricing\PricingRepository; use VO\Pricing\PricingService;

final class OrderUsageTest extends TestCase
{
    public function testConfirmedOrderRecordsDiscountsAndIncrementsUsageOnce(): void
    {
        $s = $this->db();
        try { [$svc,$cart,$pricing] = $this->services($s); $ids = $this->seed($s); $h = hash('sha256','usage-a'); $cart->addToCart($h,$ids['item'],$ids['variant'],1,[]); $cart->applyCoupon($h,'SAVE'); $cart->setCheckoutData($h,['fulfillment'=>'pickup','branch_id'=>1]); $accepted = $this->accepted($pricing,$s,$h); $o = $svc->createFromCart($h,'usage-key',$accepted,[]); $svc->createFromCart($h,'usage-key',$accepted,[]);
            $this->assertSame(1,(int)$s->pdo->query('SELECT times_used FROM promotions WHERE id=' . $ids['promo'])->fetchColumn()); $this->assertSame(1,(int)$s->pdo->query("SELECT times_used FROM coupons WHERE code='SAVE'")->fetchColumn());
            $this->assertSame(2,(int)$s->pdo->query('SELECT COUNT(*) FROM promotion_usage WHERE order_id=' . (int)$o['id'])->fetchColumn()); $this->assertSame(2,(int)$s->pdo->query('SELECT COUNT(*) FROM order_discounts WHERE order_id=' . (int)$o['id'])->fetchColumn());
        } finally { $s->drop(); }
    }
    private function db(): ScratchDatabase { $s=ScratchDatabase::create('vo_orders7_test_'); (new MigrationRunner($s->connection(), dirname(__DIR__).'/api/database/migrations'))->run(); $s->pdo->exec("INSERT INTO businesses (name,slug) VALUES ('Demo','demo')"); $s->pdo->exec("INSERT INTO branches (business_id,name,is_active) VALUES (1,'Main',1)"); $s->pdo->exec("INSERT INTO branch_settings (branch_id,setting_key,setting_value) VALUES (1,'minimum_pickup_cents','0')"); return $s; }
    private function services(ScratchDatabase $s): array { $pricing=new PricingService(new PricingRepository($s->pdo)); $db=$s->connection(); $repo=new OrderRepository($db); return [new OrderService($db,$repo,new DbIdempotencyStore($db),$pricing), new CartService(new CartRepository($s->pdo),$pricing), $pricing]; }
    private function seed(ScratchDatabase $s): array { $s->pdo->exec("INSERT INTO categories (id,name,slug) VALUES (1,'Food','food')"); $s->pdo->exec("INSERT INTO catalog_items (category_id,type,name,slug,base_price_cents,requires_variant,allows_delivery,is_active) VALUES (1,'product','Burger','burger',1000,0,1,1)"); $item=(int)$s->pdo->lastInsertId(); $s->pdo->exec("INSERT INTO item_variants (item_id,name,price_cents,is_active) VALUES ($item,'Default',1000,1)"); $variant=(int)$s->pdo->lastInsertId(); $s->pdo->exec("INSERT INTO branch_items (branch_id,item_id,is_available,stock_mode,stock_quantity) VALUES (1,$item,1,'unlimited',0)"); $s->pdo->exec("INSERT INTO branch_variants (branch_id,variant_id,is_available) VALUES (1,$variant,1)"); $s->pdo->exec("INSERT INTO promotions (name,type,priority,is_stackable) VALUES ('Order 10','min_amount_pct',1,1)"); $promo=(int)$s->pdo->lastInsertId(); $s->pdo->exec("INSERT INTO promotion_rules (promotion_id,scope,discount_basis_points,min_amount_cents) VALUES ($promo,'order',1000,100)"); $s->pdo->exec("INSERT INTO coupons (code,discount_basis_points,min_amount_cents) VALUES ('SAVE',1000,100)"); return ['item'=>$item,'variant'=>$variant,'promo'=>$promo]; }
    private function accepted(PricingService $pricing, ScratchDatabase $s, string $hash): array { $c=$s->pdo->query("SELECT * FROM carts WHERE token_hash=".$s->pdo->quote($hash))->fetch(PDO::FETCH_ASSOC); $rows=$s->pdo->query('SELECT * FROM cart_items WHERE cart_id='.(int)$c['id'].' ORDER BY id')->fetchAll(PDO::FETCH_ASSOC); $q=$pricing->quote(['branch_id'=>(int)$c['branch_id'],'fulfillment'=>$c['fulfillment'],'coupon_code'=>$c['coupon_code'],'items'=>array_map(fn($r)=>['item_id'=>(int)$r['item_id'],'variant_id'=>(int)$r['variant_id'],'quantity'=>(int)$r['qty']],$rows)]); return $q + ['accepted_grand_total_cents'=>$q['grand_total_cents'],'accepted_lines'=>array_map(fn($l)=>['line_total_cents'=>$l['line_total_cents']],$q['lines'])]; }
}
