<?php use VO\Support\Template; use VO\Cart\CartController; ob_start(); ?>
<?php if (!$order): ?><h1>Pedido no encontrado</h1><p>No pudimos encontrar ese pedido.</p><?php else: ?>
<p><a href="/">← Volver al catálogo</a></p><h1>Pedido <?= Template::e($order['number']) ?></h1><p class="notice">Estado: <strong>Pendiente</strong></p>
<section class="card"><h2>Contacto</h2><p><?= Template::e($order['customer_name'] ?? 'Cliente') ?></p><p><?= Template::e($order['customer_phone'] ?? '') ?></p><p><?= Template::e($order['customer_email'] ?? '') ?></p><?php if (!empty($order['customer_note'])): ?><p>Nota: <?= Template::e($order['customer_note']) ?></p><?php endif; ?></section>
<section class="card"><h2>Ítems</h2><ul><?php foreach ($items as $item): ?><li><?= Template::e($item['item_name']) ?><?php if ($item['variant_name']): ?> (<?= Template::e($item['variant_name']) ?>)<?php endif; ?> × <?= (int)$item['quantity'] ?> — <?= Template::e(CartController::money((int)$item['line_total_cents'])) ?><?php if ($item['modifiers']): ?><ul><?php foreach ($item['modifiers'] as $mod): ?><li><?= Template::e($mod['group_name']) ?>: <?= Template::e($mod['modifier_name']) ?></li><?php endforeach; ?></ul><?php endif; ?></li><?php endforeach; ?></ul></section>
<?php if ($address): ?><section class="card"><h2>Entrega</h2><p><?= Template::e(($address['street'] ?? '') . ' ' . ($address['city'] ?? '')) ?></p></section><?php endif; ?>
<section class="card"><h2>Detalle de precios</h2><table><tr><td>Ítems</td><td><?= Template::e(CartController::money((int)$order['gross_items_cents'])) ?></td></tr><tr><td>Promos</td><td>- <?= Template::e(CartController::money((int)$order['item_promotions_cents'] + (int)$order['order_promotions_cents'])) ?></td></tr><tr><td>Cupón</td><td>- <?= Template::e(CartController::money((int)$order['coupon_discount_cents'])) ?></td></tr><tr><td>Descuento por pago</td><td>- <?= Template::e(CartController::money((int)$order['payment_discount_cents'])) ?></td></tr><tr><td>Envío</td><td><?= Template::e(CartController::money((int)$order['delivery_fee_cents'])) ?></td></tr><tr><th>Total</th><th><?= Template::e(CartController::money((int)$order['grand_total_cents'])) ?></th></tr></table></section>
<?php endif; ?>
<?php $content = ob_get_clean(); require dirname(__DIR__, 2) . '/Catalog/templates/layout.php'; ?>
