<?php declare(strict_types=1);
namespace VO\Catalog;

use InvalidArgumentException; use PDO; use VO\Audit\AuditService;

final class CatalogService
{
    public function __construct(private CatalogRepository $repo, private PDO $pdo, private ?AuditService $audit = null, private ?string $requestId = null) { $this->audit ??= new AuditService($pdo); }
    public function createCategory(array $data, ?array $actor = null): int { return $this->tx(fn() => $this->saveCategory($data, null, $actor)); }
    public function updateCategory(int $id, array $data, ?array $actor = null): int { $data['id'] = $id; return $this->tx(fn() => $this->saveCategory($data, $id, $actor)); }
    public function archiveCategory(int $id, ?array $actor = null): void { $this->tx(function() use($id,$actor){ $this->repo->archive('categories',$id); $this->log($actor,'catalog.archived','category:'.$id,[]); }); }
    public function createItem(array $data, array $variants = [], ?array $actor = null): int { return $this->tx(fn() => $this->saveItem($data, $variants, null, $actor)); }
    public function updateItem(int $id, array $data, array $variants = [], ?array $actor = null): int { $data['id'] = $id; return $this->tx(fn() => $this->saveItem($data, $variants, $id, $actor)); }
    public function archiveItem(int $id, ?array $actor = null): void { $this->tx(function() use($id,$actor){ $this->repo->archive('catalog_items',$id); $this->log($actor,'catalog.archived','catalog_item:'.$id,[]); }); }
    public function saveVariants(int $itemId, array $variants, ?array $actor = null): void { foreach ($variants as $v) { $d = $this->variant($v); $old = $d['id'] !== null ? $this->repo->findVariant((int)$d['id']) : null; $vid = $this->repo->saveVariant($itemId, $d); if ($old !== null && (int)$old['item_id'] === $itemId && (int)$old['is_active'] !== (int)$d['is_active']) $this->log($actor,'catalog.availability_changed','item_variant:'.$vid,['old_available'=>(int)$old['is_active'],'new_available'=>(int)$d['is_active'],'target_type'=>'item_variant','target_id'=>$vid]); } }
    public function saveModifierGroup(array $data, ?array $actor = null): int { return $this->tx(function() use($data,$actor){ $d = $this->modifierGroup($data); $id = $this->repo->saveModifierGroup($d); $this->log($actor, isset($data['id']) ? 'catalog.updated' : 'catalog.created', 'modifier_group:'.$id, []); return $id; }); }
    public function linkModifierGroup(int $itemId, int $groupId, int $sort = 0): void { $this->repo->linkModifierGroup($itemId, $groupId, $sort); }
    public function saveBranchCatalog(int $branchId, int $itemId, array $data, string $itemType = 'product', ?array $actor = null): void { $this->tx(function() use($branchId,$itemId,$data,$itemType,$actor){ $old = $this->repo->findBranchItem($branchId, $itemId); $available = (bool)($data['is_available'] ?? true); $stock = $itemType === 'service' ? 'none' : ($data['stock_mode'] ?? 'none'); $this->repo->saveBranchCatalog($branchId,$itemId,$available,$this->cents($data['price_override_cents'] ?? null),$stock); if ($old !== null && (int)$old['is_available'] !== ($available ? 1 : 0)) $this->log($actor,'catalog.availability_changed','catalog_item:'.$itemId,['old_available'=>(int)$old['is_available'],'new_available'=>$available ? 1 : 0,'branch_id'=>$branchId,'target_type'=>'catalog_item','target_id'=>$itemId]); $this->log($actor,'catalog.branch_override_updated','catalog_item:'.$itemId,['branch_id'=>$branchId]); }); }
    public function resolveDisplayPrice(array $item, ?array $branchItem = null, ?array $variant = null, ?array $branchVariant = null): ?int { return CatalogPriceResolver::resolve($item, $branchItem, $variant, $branchVariant); }

    private function saveCategory(array $data, ?int $id, ?array $actor): int { $d = ['id'=>$id,'parent_id'=>$this->nullableInt($data['parent_id'] ?? null),'name'=>$this->required($data,'name'),'slug'=>$this->slug($data['slug'] ?? ''),'description'=>$data['description'] ?? null,'sort_order'=>(int)($data['sort_order'] ?? 0),'is_active'=>empty($data['is_active']) ? 0 : 1]; if ($this->repo->slugExists('categories',$d['slug'],$id)) throw new InvalidArgumentException('El slug ya existe.'); $new = $this->repo->saveCategory($d); $this->log($actor, $id ? 'catalog.updated' : 'catalog.created', 'category:'.$new, []); return $new; }
    private function saveItem(array $data, array $variants, ?int $id, ?array $actor): int { $old = $id ? $this->repo->findItemForEdit($id) : null; $d = ['id'=>$id,'category_id'=>$this->nullableInt($data['category_id'] ?? null),'type'=>$data['type'] ?? 'product','name'=>$this->required($data,'name'),'slug'=>$this->slug($data['slug'] ?? ''),'description'=>$data['description'] ?? null,'base_price_cents'=>$this->cents($data['base_price_cents'] ?? null),'requires_variant'=>empty($data['requires_variant']) ? 0 : 1,'allows_pickup'=>array_key_exists('allows_pickup',$data) ? (int)(bool)$data['allows_pickup'] : 1,'allows_delivery'=>empty($data['allows_delivery']) ? 0 : 1,'is_active'=>array_key_exists('is_active',$data) ? (int)(bool)$data['is_active'] : 1]; if (!in_array($d['type'], ['product','service'], true)) throw new InvalidArgumentException('Invalid catalog item type.'); if ($d['type'] === 'service' && $d['allows_delivery']) throw new InvalidArgumentException('Un servicio no puede habilitar envío.'); if ($this->repo->slugExists('catalog_items',$d['slug'],$id)) throw new InvalidArgumentException('El slug ya existe.'); if ($d['requires_variant'] && !$this->hasActiveVariant($variants, $id)) throw new InvalidArgumentException('El producto requiere al menos una variante activa.'); $new = $this->repo->saveItem($d); $this->saveVariants($new, $variants, $actor); $this->syncImages($new, $data['images'] ?? null); $this->log($actor, $id ? 'catalog.updated' : 'catalog.created', 'catalog_item:'.$new, []); if ($old && (int)($old['base_price_cents'] ?? -1) !== (int)($d['base_price_cents'] ?? -1)) $this->log($actor,'catalog.price_changed','catalog_item:'.$new,['old_cents'=>$old['base_price_cents'] === null ? null : (int)$old['base_price_cents'],'new_cents'=>$d['base_price_cents'],'target_type'=>'catalog_item','target_id'=>$new]); if ($old && (int)$old['is_active'] !== (int)$d['is_active']) $this->log($actor,'catalog.availability_changed','catalog_item:'.$new,['old_available'=>(int)$old['is_active'],'new_available'=>(int)$d['is_active'],'target_type'=>'catalog_item','target_id'=>$new]); return $new; }
    private function hasActiveVariant(array $variants, ?int $itemId): bool { foreach ($variants as $v) if (($v['is_active'] ?? true) && !($v['archived_at'] ?? false) && trim((string)($v['name'] ?? '')) !== '') return true; return $itemId ? count($this->repo->activeVariants($itemId)) > 0 : false; }
    private function variant(array $d): array { return ['id'=>$d['id'] ?? null,'name'=>$this->required($d,'name'),'sku'=>$d['sku'] ?? null,'price_cents'=>$this->cents($d['price_cents'] ?? null),'is_active'=>array_key_exists('is_active',$d) ? (int)(bool)$d['is_active'] : 1,'sort_order'=>(int)($d['sort_order'] ?? 0)]; }
    private function modifierGroup(array $d): array { $selection = $d['selection'] ?? 'single'; $min = (int)($d['min_select'] ?? 0); $max = $selection === 'single' ? 1 : (isset($d['max_select']) ? (int)$d['max_select'] : null); if ($max !== null && $min > $max) throw new InvalidArgumentException('La selección mínima no puede superar la máxima.'); return ['id'=>$d['id'] ?? null,'name'=>$this->required($d,'name'),'is_required'=>empty($d['is_required']) ? 0 : 1,'selection'=>$selection,'min_select'=>$min,'max_select'=>$max,'sort_order'=>(int)($d['sort_order'] ?? 0),'is_active'=>array_key_exists('is_active',$d) ? (int)(bool)$d['is_active'] : 1]; }
    private function required(array $d, string $key): string { $v = trim((string)($d[$key] ?? '')); if ($v === '') throw new InvalidArgumentException($key === 'name' ? 'El nombre es obligatorio.' : 'Required field missing.'); return $v; }
    private function slug(string $slug): string { $slug = trim($slug); if ($slug === '') throw new InvalidArgumentException('Required field missing.'); return $slug; }
    private function cents(mixed $v): ?int { if ($v === null || $v === '') return null; $i = filter_var($v, FILTER_VALIDATE_INT); if ($i === false || $i < 0) throw new InvalidArgumentException('Invalid cents value.'); return $i; }
    private function nullableInt(mixed $v): ?int { return ($v === null || $v === '') ? null : (int)$v; }
    private function syncImages(int $itemId, ?array $images): void { if ($images === null) return; $own = array_map('intval', array_column($this->repo->allImagesForItem($itemId), 'id')); $keep = []; foreach ($images as $img) { $filename = trim((string)($img['filename'] ?? '')); if ($filename === '') continue; $id = $this->nullableInt($img['id'] ?? null); if ($id === null || !in_array($id, $own, true)) $id = null; $alt = trim((string)($img['alt'] ?? '')); $keep[] = $this->repo->saveItemImage(['id'=>$id,'item_id'=>$itemId,'filename'=>$filename,'alt_text'=>$alt !== '' ? $alt : null,'sort_order'=>(int)($img['sort'] ?? 0),'is_active'=>1]); } $this->repo->deactivateImagesExcept($itemId, $keep); }
    private function tx(callable $fn): mixed { $this->pdo->beginTransaction(); try { $r = $fn(); $this->pdo->commit(); return $r; } catch (\Throwable $e) { if ($this->pdo->inTransaction()) $this->pdo->rollBack(); throw $e; } }
    private function log(?array $actor, string $action, string $entity, array $meta): void { $this->audit?->append($actor ?? ['type'=>'system'], $action, $entity, $meta, $this->requestId); }
}
