<?php use VO\Support\Template; use VO\Reports\ReportsService; ob_start(); ?>
<section class="top"><div><p class="eyebrow"><?= Template::e($user['business_name'] ?? '') ?></p><h1>Panel de administración</h1><p class="muted">Hola, <?= Template::e($user['name'] ?? '') ?>.</p></div><form method="post" action="/admin/logout"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><button class="btn secondary">Cerrar sesión</button></form></section>
<?php if ($flashOk): ?><section class="card"><p><strong><?= Template::e($flashOk) ?></strong></p></section><?php endif; ?>
<?php if ($flashErr): ?><section class="card"><p class="error"><?= Template::e($flashErr) ?></p></section><?php endif; ?>
<?php if ($quick['pending'] || $quick['ready'] || (int)$quick['payments'] > 0): ?><section class="card quick"><h2>Acciones rápidas</h2>
<?php if ($quick['pending']): ?><div class="quick-group"><h3>Pedidos pendientes</h3><?php foreach ($quick['pending'] as $o): ?><article class="quick-row"><a href="/admin/pedidos/<?= (int)$o['id'] ?>"><?= Template::e($o['number']) ?></a><span class="muted">$ <?= number_format(((int)$o['grand_total_cents']) / 100, 2, ',', '.') ?></span><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/aceptar"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><input type="hidden" name="back" value="dashboard"><button class="btn">Aceptar</button></form></article><?php endforeach; ?></div><?php endif; ?>
<?php if ($quick['ready']): ?><div class="quick-group"><h3>Listos para completar</h3><?php foreach ($quick['ready'] as $o): ?><article class="quick-row"><a href="/admin/pedidos/<?= (int)$o['id'] ?>"><?= Template::e($o['number']) ?></a><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/completar"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><input type="hidden" name="back" value="dashboard"><button class="btn">Completar</button></form></article><?php endforeach; ?></div><?php endif; ?>
<?php if ((int)$quick['payments'] > 0): ?><p class="quick-pay"><a href="/admin/pagos?state=pending_verification">Pagos por verificar: <?= (int)$quick['payments'] ?></a></p><?php endif; ?>
</section><?php endif; ?>
<section class="grid"><?php foreach ([['Ventas de hoy', ReportsService::money((int)$metrics['ventas_hoy'])], ['Pedidos de hoy', (string)(int)$metrics['pedidos_hoy']], ['Ticket promedio', ReportsService::money((int)$metrics['ticket_promedio'])], ['Nuevos', (string)(int)$metrics['nuevos']], ['Preparando', (string)(int)$metrics['preparando']], ['Listos', (string)(int)$metrics['listos']], ['Buscando delivery', (string)(int)$metrics['buscando_delivery']], ['En camino', (string)(int)$metrics['en_camino']], ['Cancelados', (string)(int)$metrics['cancelados']], ['Rechazados', (string)(int)$metrics['rechazados']], ['Stock bajo', (string)(int)$metrics['stock_bajo']]] as [$label, $value]): ?><article class="card"><h2><?= Template::e($label) ?></h2><p><?= Template::e($value) ?></p></article><?php endforeach; ?></section>
<section class="grid"><?php foreach(['Pedidos'=>'/admin/pedidos','Operación'=>'/admin/operacion','Catálogo'=>'/admin/catalogo','Pagos'=>'/admin/pagos','Configuración'=>'/admin/configuracion','Notificaciones'=>'/admin/notificaciones','Sucursales'=>null,'Repartos'=>'/admin/delivery','Reportes'=>'/admin/reportes'] as $name=>$href):?><article class="card"><h2><?php if($href):?><a href="<?= Template::e($href) ?>"><?= Template::e($name) ?></a><?php else:?><?= Template::e($name) ?><?php endif;?></h2><?php if(!$href):?><p class="muted">Módulo pendiente.</p><?php endif;?></article><?php endforeach;?></section>
<?php $content = ob_get_clean(); $title = 'Panel de administración'; require __DIR__ . '/layout.php'; ?>
