<?php use VO\Support\Template; ob_start(); ?>
<h1>Operación</h1>
<?php if ($flashOk): ?><section class="card"><p><strong><?= Template::e($flashOk) ?></strong></p></section><?php endif; ?>
<?php if ($flashErr): ?><section class="card"><p class="error"><?= Template::e($flashErr) ?></p></section><?php endif; ?>
<section class="card"><form method="get" action="/admin/operacion"><label>Sucursal <select name="branch_id"><option value="">Todas</option><?php foreach ($branches as $b): ?><option value="<?= (int)$b['id'] ?>"<?= $branchId === (int)$b['id'] ? ' selected' : '' ?>><?= Template::e($b['name']) ?></option><?php endforeach; ?></select></label> <button class="btn">Filtrar</button></form> <p><a href="<?= Template::e($refreshUrl) ?>">Actualizar</a> · <?php if ($auto): ?><a href="<?= Template::e($refreshUrl) ?>">Detener actualización automática</a><?php else: ?><a href="<?= Template::e($autoOnUrl) ?>">Actualización automática (30 s)</a><?php endif; ?></p></section>
<?php foreach ($sections as $status => $label): ?>
<section class="card"><h2><?= Template::e($label) ?></h2>
<?php foreach ($orders[$status] as $o): ?>
<article><p><a href="/admin/pedidos/<?= (int)$o['id'] ?>"><?= Template::e($o['number']) ?></a> · <?= Template::e($o['branch_name']) ?> · <?= (int)$o['item_count'] ?> ítems · $ <?= number_format(((int)$o['grand_total_cents']) / 100, 2, ',', '.') ?> · hace <?= Template::e($o['age']) ?></p>
<p><?php foreach ($actions[$status] as $a): if ($a['accion'] === 'cancelar') continue; ?><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/<?= Template::e($a['accion']) ?>" style="display:inline"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><?php if ($branchId !== null): ?><input type="hidden" name="branch_id" value="<?= $branchId ?>"><?php endif; if ($auto): ?><input type="hidden" name="auto" value="1"><?php endif; ?><button class="btn"><?= Template::e($a['label']) ?></button></form> <?php endforeach; ?>
<?php if (in_array('cancelar', array_column($actions[$status], 'accion'), true)): ?><details><summary>Cancelar</summary><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/cancelar"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><?php if ($branchId !== null): ?><input type="hidden" name="branch_id" value="<?= $branchId ?>"><?php endif; if ($auto): ?><input type="hidden" name="auto" value="1"><?php endif; ?><label>Motivo <input name="reason" required maxlength="191"></label> <button class="btn">Confirmar cancelación</button></form></details><?php endif; ?></p>
<?php $d = $deliveries[(int)$o['id']] ?? null; if ($d !== null): $p = $d['panel']; ?>
<p class="muted">Envío: <?= Template::e($p['state_label']) ?><?php if ($d['person_name'] !== ''): ?> · Repartidor: <?= Template::e($d['person_name']) ?><?php endif; ?></p>
<p><?php if ($p['assign']): ?><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/asignar" style="display:inline"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><?php if ($branchId !== null): ?><input type="hidden" name="branch_id" value="<?= $branchId ?>"><?php endif; if ($auto): ?><input type="hidden" name="auto" value="1"><?php endif; ?><label>Repartidor <select name="person_id" required><?php foreach ($d['persons'] as $per): ?><option value="<?= (int)$per['id'] ?>"><?= Template::e($per['name']) ?></option><?php endforeach; ?></select></label> <button class="btn">Asignar</button></form> <?php endif; ?>
<?php if ($p['reassign']): ?><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/reasignar" style="display:inline"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><?php if ($branchId !== null): ?><input type="hidden" name="branch_id" value="<?= $branchId ?>"><?php endif; if ($auto): ?><input type="hidden" name="auto" value="1"><?php endif; ?><label>Repartidor <select name="person_id" required><?php foreach ($d['persons'] as $per): ?><option value="<?= (int)$per['id'] ?>"<?= (int)($d['delivery']['delivery_person_id'] ?? 0) === (int)$per['id'] ? ' selected' : '' ?>><?= Template::e($per['name']) ?></option><?php endforeach; ?></select></label> <button class="btn">Reasignar</button></form> <?php endif; ?>
<?php if ($p['pickup']): ?><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/retirar" style="display:inline"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><?php if ($branchId !== null): ?><input type="hidden" name="branch_id" value="<?= $branchId ?>"><?php endif; if ($auto): ?><input type="hidden" name="auto" value="1"><?php endif; ?><button class="btn">Retiró</button></form> <?php endif; ?>
<?php if ($p['deliver']): ?><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/entregar" style="display:inline"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><?php if ($branchId !== null): ?><input type="hidden" name="branch_id" value="<?= $branchId ?>"><?php endif; if ($auto): ?><input type="hidden" name="auto" value="1"><?php endif; ?><label>PIN <input name="pin" inputmode="numeric" pattern="\d{6}" maxlength="6" size="6" required></label> <button class="btn">Entregar</button></form> <?php endif; ?>
<?php if ($p['fail']): ?><details><summary>Falló</summary><form method="post" action="/admin/operacion/<?= (int)$o['id'] ?>/fallar"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><?php if ($branchId !== null): ?><input type="hidden" name="branch_id" value="<?= $branchId ?>"><?php endif; if ($auto): ?><input type="hidden" name="auto" value="1"><?php endif; ?><label>Motivo <input name="reason" required maxlength="191"></label> <button class="btn">Confirmar fallo</button></form></details><?php endif; ?></p>
<?php endif; ?>
</article>
<?php endforeach; ?>
<?php if (!$orders[$status]): ?><p class="muted">No hay pedidos en esta sección.</p><?php endif; ?>
</section>
<?php endforeach; ?>
<?php $content = ob_get_clean(); $title = 'Operación'; $autoRefresh = $auto; require __DIR__ . '/layout.php'; ?>
