<?php use VO\Support\Template; ob_start(); ?>
<h1>Pedido <?= Template::e($order['number']) ?></h1><?php if ($flashOk): ?><section class="card"><p><strong><?= Template::e($flashOk) ?></strong></p></section><?php endif; ?><?php if ($flashErr): ?><section class="card"><p class="error"><?= Template::e($flashErr) ?></p></section><?php endif; ?><section class="card"><p><strong>Estado:</strong> <?= Template::e($order['status']) ?> · <strong>Sucursal:</strong> <?= Template::e($order['branch_name']) ?></p><p><strong>Contacto:</strong> <?= Template::e($order['customer_name'] ?? '') ?> · <?= Template::e($order['customer_phone'] ?? '') ?> · <?= Template::e($order['customer_email'] ?? '') ?></p><p><strong>Total:</strong> $ <?= number_format(((int)$order['grand_total_cents'])/100,2,',','.') ?></p></section>
<?php if ($actions): $cancel = array_values(array_filter($actions, fn(array $a): bool => $a['accion'] === 'cancelar')); $others = array_values(array_filter($actions, fn(array $a): bool => $a['accion'] !== 'cancelar')); ?>
<section class="card"><h2>Acciones</h2><?php if ($others): ?><p><?php foreach ($others as $a): ?><form method="post" action="/admin/operacion/<?= (int)$order['id'] ?>/<?= Template::e($a['accion']) ?>" style="display:inline"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><input type="hidden" name="back" value="detail"><button class="btn"><?= Template::e($a['label']) ?></button></form> <?php endforeach; ?></p><?php endif; ?><?php if ($cancel): ?><form method="post" action="/admin/operacion/<?= (int)$order['id'] ?>/cancelar"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><input type="hidden" name="back" value="detail"><label>Motivo <input name="reason" required maxlength="191"></label> <button class="btn">Cancelar pedido</button></form><?php endif; ?></section>
<?php endif; ?>
<section class="card"><h2>Ítems</h2><?php foreach ($items as $i): ?><p><?= (int)$i['quantity'] ?> × <?= Template::e($i['item_name']) ?> <?= Template::e($i['variant_name'] ?? '') ?> · $ <?= number_format(((int)$i['line_total_cents'])/100,2,',','.') ?></p><?php foreach ($i['modifiers'] as $m): ?><p class="muted">+ <?= Template::e($m['group_name']) ?>: <?= Template::e($m['modifier_name']) ?></p><?php endforeach; endforeach; ?></section>
<?php if ($address): ?><section class="card"><h2>Dirección</h2><p><?= Template::e($address['recipient_name'] ?? '') ?> · <?= Template::e($address['street'] ?? '') ?> · <?= Template::e($address['city'] ?? '') ?> · <?= Template::e($address['notes'] ?? '') ?></p></section><?php endif; ?>
<section class="card"><h2>Descuentos</h2><?php foreach ($discounts as $d): ?><p><?= Template::e($d['kind']) ?> <?= Template::e($d['code'] ?? '') ?> · $ <?= number_format(((int)$d['amount_cents'])/100,2,',','.') ?></p><?php endforeach; if (!$discounts): ?><p>Sin descuentos.</p><?php endif; ?></section>
<section class="card"><h2>Totales</h2><p>Productos: $ <?= number_format(((int)$order['gross_items_cents'])/100,2,',','.') ?> · Mercadería: $ <?= number_format(((int)$order['merchandise_total_cents'])/100,2,',','.') ?> · Envío: $ <?= number_format(((int)$order['delivery_fee_cents'])/100,2,',','.') ?></p></section>
<?php if($payment): ?><section class="card"><h2>Pago</h2><p><?= Template::e($payment['method']) ?> · <?= Template::e($payment['state']) ?> · <a href="/admin/pagos/<?= (int)$payment['id'] ?>">Ver pago y acciones</a></p></section><?php endif; ?>
<?php if ($delivery): $d = $delivery['delivery']; $p = $delivery['panel']; ?>
<section class="card"><h2>Entrega</h2><p><strong>Estado:</strong> <?= Template::e($p['state_label']) ?><?php if ($delivery['person_name'] !== ''): ?> · <strong>Repartidor:</strong> <?= Template::e($delivery['person_name']) ?><?php endif; ?><?php if ((string)($d['failed_reason'] ?? '') !== ''): ?> · <strong>Motivo del fallo:</strong> <?= Template::e((string)$d['failed_reason']) ?><?php endif; ?></p>
<?php if ($p['assign'] || $p['reassign']): ?><form method="post" action="/admin/operacion/<?= (int)$order['id'] ?>/<?= $p['assign'] ? 'asignar' : 'reasignar' ?>"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><input type="hidden" name="back" value="detail"><label>Repartidor <select name="person_id" required><?php foreach ($delivery['persons'] as $per): ?><option value="<?= (int)$per['id'] ?>"<?= (int)($d['delivery_person_id'] ?? 0) === (int)$per['id'] ? ' selected' : '' ?>><?= Template::e($per['name']) ?></option><?php endforeach; ?></select></label> <button class="btn"><?= $p['assign'] ? 'Asignar' : 'Reasignar' ?></button></form><?php endif; ?>
<?php if ($p['pickup']): ?><form method="post" action="/admin/operacion/<?= (int)$order['id'] ?>/retirar"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><input type="hidden" name="back" value="detail"><button class="btn">Retiró</button></form><?php endif; ?>
<?php if ($p['deliver']): ?><form method="post" action="/admin/operacion/<?= (int)$order['id'] ?>/entregar"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><input type="hidden" name="back" value="detail"><label>PIN <input name="pin" inputmode="numeric" pattern="\d{6}" maxlength="6" size="6" required></label> <button class="btn">Entregar</button></form><?php endif; ?>
<?php if ($p['fail']): ?><details><summary>Falló</summary><form method="post" action="/admin/operacion/<?= (int)$order['id'] ?>/fallar"><input type="hidden" name="csrf" value="<?= Template::e($csrf) ?>"><input type="hidden" name="back" value="detail"><label>Motivo <input name="reason" required maxlength="191"></label> <button class="btn">Confirmar fallo</button></form></details><?php endif; ?>
</section>
<?php endif; ?>
<section class="card"><h2>Movimientos de stock</h2><?php foreach ($movements as $m): ?><p><?= Template::e($m['reason']) ?> · <?= (int)$m['quantity_delta'] ?> · item <?= (int)$m['item_id'] ?></p><?php endforeach; if (!$movements): ?><p>Sin movimientos.</p><?php endif; ?></section>
<?php $content = ob_get_clean(); $title = 'Pedido ' . $order['number']; require __DIR__ . '/layout.php'; ?>
