<?php declare(strict_types=1);
use VO\Database\Connection;

return static function (Connection $db): void {
    foreach ([
        "CREATE TABLE categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,parent_id BIGINT UNSIGNED NULL,name VARCHAR(191) NOT NULL,slug VARCHAR(191) NOT NULL UNIQUE,description TEXT NULL,sort_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,archived_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_categories_parent_active (parent_id,is_active,archived_at,sort_order),CONSTRAINT fk_categories_parent FOREIGN KEY(parent_id) REFERENCES categories(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE catalog_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id BIGINT UNSIGNED NULL,type ENUM('product','service') NOT NULL,name VARCHAR(191) NOT NULL,slug VARCHAR(191) NOT NULL UNIQUE,description TEXT NULL,base_price_cents BIGINT NULL,requires_variant TINYINT(1) NOT NULL DEFAULT 0,allows_pickup TINYINT(1) NOT NULL DEFAULT 1,allows_delivery TINYINT(1) NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,archived_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_items_category_active (category_id,is_active,archived_at),KEY idx_items_type_active (type,is_active,archived_at),CONSTRAINT fk_items_category FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE item_variants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,item_id BIGINT UNSIGNED NOT NULL,name VARCHAR(191) NOT NULL,sku VARCHAR(191) NULL,price_cents BIGINT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,archived_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_variants_item_active (item_id,is_active,archived_at,sort_order),CONSTRAINT fk_variants_item FOREIGN KEY(item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE modifier_groups (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(191) NOT NULL,is_required TINYINT(1) NOT NULL DEFAULT 0,selection ENUM('single','multi') NOT NULL DEFAULT 'single',min_select INT NOT NULL DEFAULT 0,max_select INT NULL,sort_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,archived_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_groups_active (is_active,archived_at,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE modifiers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,group_id BIGINT UNSIGNED NOT NULL,name VARCHAR(191) NOT NULL,price_delta_cents BIGINT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,archived_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_modifiers_group_active (group_id,is_active,archived_at,sort_order),CONSTRAINT fk_modifiers_group FOREIGN KEY(group_id) REFERENCES modifier_groups(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE item_modifier_group (item_id BIGINT UNSIGNED NOT NULL,group_id BIGINT UNSIGNED NOT NULL,sort_order INT NOT NULL DEFAULT 0,PRIMARY KEY(item_id,group_id),KEY idx_img_group (group_id),CONSTRAINT fk_img_item FOREIGN KEY(item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT,CONSTRAINT fk_img_group FOREIGN KEY(group_id) REFERENCES modifier_groups(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE branch_items (branch_id BIGINT UNSIGNED NOT NULL,item_id BIGINT UNSIGNED NOT NULL,is_available TINYINT(1) NOT NULL DEFAULT 1,price_override_cents BIGINT NULL,stock_mode ENUM('none','simple','unlimited') NOT NULL DEFAULT 'none',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(branch_id,item_id),KEY idx_branch_items_item_available (item_id,is_available),CONSTRAINT fk_branch_items_branch FOREIGN KEY(branch_id) REFERENCES branches(id) ON DELETE CASCADE,CONSTRAINT fk_branch_items_item FOREIGN KEY(item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE branch_variants (branch_id BIGINT UNSIGNED NOT NULL,variant_id BIGINT UNSIGNED NOT NULL,is_available TINYINT(1) NOT NULL DEFAULT 1,price_override_cents BIGINT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(branch_id,variant_id),KEY idx_branch_variants_variant_available (variant_id,is_available),CONSTRAINT fk_branch_variants_branch FOREIGN KEY(branch_id) REFERENCES branches(id) ON DELETE CASCADE,CONSTRAINT fk_branch_variants_variant FOREIGN KEY(variant_id) REFERENCES item_variants(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE item_images (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,item_id BIGINT UNSIGNED NOT NULL,filename VARCHAR(255) NOT NULL,alt_text VARCHAR(255) NULL,sort_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_images_item_active (item_id,is_active,sort_order),CONSTRAINT fk_images_item FOREIGN KEY(item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ] as $sql) $db->execute($sql);
    $db->execute("INSERT INTO permissions(permission_key,label) SELECT 'products.manage','products.manage' WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE permission_key='products.manage')");
    $db->execute("INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.permission_key='products.manage' WHERE r.name='owner' AND NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=r.id AND rp.permission_id=p.id)");
};
