<?php declare(strict_types=1);
use VO\Database\Connection;

return static function (Connection $db): void {
    foreach ([
        "CREATE TABLE promotions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(191) NOT NULL,type ENUM('product_pct','product_fixed','category_pct','min_amount_pct','payment_pct','scheduled_price') NOT NULL,priority INT NOT NULL DEFAULT 0,is_stackable TINYINT(1) NOT NULL DEFAULT 0,starts_at DATETIME NULL,ends_at DATETIME NULL,usage_limit INT NULL,times_used INT NOT NULL DEFAULT 0,archived_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_promotions_active (type,priority,archived_at,starts_at,ends_at),KEY idx_promotions_usage (usage_limit,times_used)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE promotion_rules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,promotion_id BIGINT UNSIGNED NOT NULL,scope ENUM('item','category','order','payment_method') NOT NULL,scope_id BIGINT UNSIGNED NULL,payment_method VARCHAR(64) NULL,discount_basis_points INT NULL,fixed_cents BIGINT NULL,scheduled_price_cents BIGINT NULL,min_amount_cents BIGINT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_rules_promotion (promotion_id),KEY idx_rules_scope (scope,scope_id),KEY idx_rules_payment (payment_method),CONSTRAINT fk_promotion_rules_promotion FOREIGN KEY(promotion_id) REFERENCES promotions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE coupons (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(64) NOT NULL,discount_basis_points INT NOT NULL,min_amount_cents BIGINT NULL,starts_at DATETIME NULL,ends_at DATETIME NULL,usage_limit INT NULL,times_used INT NOT NULL DEFAULT 0,archived_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_coupons_code (code),KEY idx_coupons_active (archived_at,starts_at,ends_at),KEY idx_coupons_usage (usage_limit,times_used)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ] as $sql) $db->execute($sql);
};
