<?php declare(strict_types=1);
use VO\Database\Connection;

return static function (Connection $db): void {
    foreach ([
        "CREATE TABLE carts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,token_hash CHAR(64) NOT NULL UNIQUE,branch_id BIGINT UNSIGNED NULL,fulfillment ENUM('pickup','delivery') NOT NULL DEFAULT 'pickup',coupon_code VARCHAR(64) NULL,payment_method VARCHAR(64) NULL,address_json JSON NULL,customer_note VARCHAR(500) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,expires_at TIMESTAMP NULL,KEY idx_carts_token_hash (token_hash),KEY idx_carts_expires (expires_at),KEY idx_carts_branch (branch_id),CONSTRAINT fk_carts_branch FOREIGN KEY(branch_id) REFERENCES branches(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE cart_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,cart_id BIGINT UNSIGNED NOT NULL,item_id BIGINT UNSIGNED NOT NULL,variant_id BIGINT UNSIGNED NULL,qty INT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_cart_line (cart_id,item_id,variant_id),KEY idx_cart_items_item (item_id),KEY idx_cart_items_variant (variant_id),CONSTRAINT chk_cart_items_qty CHECK(qty>0),CONSTRAINT fk_cart_items_cart FOREIGN KEY(cart_id) REFERENCES carts(id) ON DELETE CASCADE,CONSTRAINT fk_cart_items_item FOREIGN KEY(item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT,CONSTRAINT fk_cart_items_variant FOREIGN KEY(variant_id) REFERENCES item_variants(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE cart_item_modifiers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,cart_item_id BIGINT UNSIGNED NOT NULL,modifier_id BIGINT UNSIGNED NOT NULL,qty INT UNSIGNED NOT NULL DEFAULT 1,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_cart_item_modifier (cart_item_id,modifier_id),KEY idx_cim_modifier (modifier_id),CONSTRAINT chk_cim_qty CHECK(qty>0),CONSTRAINT fk_cim_cart_item FOREIGN KEY(cart_item_id) REFERENCES cart_items(id) ON DELETE CASCADE,CONSTRAINT fk_cim_modifier FOREIGN KEY(modifier_id) REFERENCES modifiers(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ] as $sql) $db->execute($sql);
};
