<?php declare(strict_types=1);
use VO\Database\Connection;

return static function (Connection $db): void {
    foreach ([
        "CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,business_id BIGINT UNSIGNED NOT NULL,method ENUM('transfer','mercadopago') NOT NULL,state ENUM('pending','approved','rejected','cancelled','pending_verification','verified','refund_pending','refund_completed') NOT NULL,amount_cents INT NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'ARS',external_reference VARCHAR(190) NULL UNIQUE,provider_payment_id VARCHAR(190) NULL,provider_preference_id VARCHAR(190) NULL,provider_status VARCHAR(64) NULL,provider_status_detail VARCHAR(191) NULL,preference_init_point TEXT NULL,proof_path VARCHAR(500) NULL,verified_by BIGINT UNSIGNED NULL,verified_at DATETIME NULL,expires_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_payments_order_id (order_id),KEY idx_payments_state (state),KEY idx_payments_business_id (business_id),KEY idx_payments_provider_payment_id (provider_payment_id),KEY idx_payments_provider_preference_id (provider_preference_id),CONSTRAINT fk_payments_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE RESTRICT,CONSTRAINT fk_payments_business FOREIGN KEY(business_id) REFERENCES businesses(id) ON DELETE RESTRICT,CONSTRAINT fk_payments_verified_by FOREIGN KEY(verified_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE payment_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,payment_id BIGINT UNSIGNED NULL,business_id BIGINT UNSIGNED NOT NULL,provider VARCHAR(32) NOT NULL DEFAULT 'internal',event_type VARCHAR(100) NOT NULL,provider_event_id VARCHAR(190) NULL,external_reference VARCHAR(190) NULL,payload_json JSON NULL,signature_valid TINYINT(1) NOT NULL DEFAULT 1,result_state VARCHAR(32) NULL,received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,processed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_payment_events_provider_event (provider,provider_event_id),KEY idx_payment_events_payment_id (payment_id),KEY idx_payment_events_business_id (business_id),KEY idx_payment_events_external_reference (external_reference),CONSTRAINT fk_payment_events_payment FOREIGN KEY(payment_id) REFERENCES payments(id) ON DELETE SET NULL,CONSTRAINT fk_payment_events_business FOREIGN KEY(business_id) REFERENCES businesses(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ] as $sql) $db->execute($sql);
};
