<?php declare(strict_types=1);
use VO\Database\Connection;

return static function (Connection $db): void {
    foreach ([
        "CREATE TABLE delivery_zones (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,branch_id BIGINT UNSIGNED NOT NULL,name VARCHAR(191) NOT NULL,match_terms VARCHAR(500) NOT NULL,customer_rate_cents INT NOT NULL DEFAULT 0,driver_payout_cents INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_delivery_zones_branch_active (branch_id,is_active),CONSTRAINT fk_delivery_zones_branch FOREIGN KEY(branch_id) REFERENCES branches(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE delivery_persons (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,business_id BIGINT UNSIGNED NOT NULL,name VARCHAR(191) NOT NULL,phone VARCHAR(64) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_delivery_persons_business (business_id,is_active),CONSTRAINT fk_delivery_persons_business FOREIGN KEY(business_id) REFERENCES businesses(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE delivery_person_branches (person_id BIGINT UNSIGNED NOT NULL,branch_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(person_id,branch_id),KEY idx_dpb_branch (branch_id),CONSTRAINT fk_dpb_person FOREIGN KEY(person_id) REFERENCES delivery_persons(id) ON DELETE CASCADE,CONSTRAINT fk_dpb_branch FOREIGN KEY(branch_id) REFERENCES branches(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE deliveries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,delivery_person_id BIGINT UNSIGNED NULL,state ENUM('pending','assigned','picked_up','delivered','failed','cancelled') NOT NULL DEFAULT 'pending',pin_hash CHAR(64) NULL,pin_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,assigned_at DATETIME NULL,picked_up_at DATETIME NULL,delivered_at DATETIME NULL,failed_reason VARCHAR(191) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_deliveries_order (order_id),KEY idx_deliveries_person_state (delivery_person_id,state),CONSTRAINT fk_deliveries_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,CONSTRAINT fk_deliveries_person FOREIGN KEY(delivery_person_id) REFERENCES delivery_persons(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "ALTER TABLE carts ADD COLUMN delivery_zone_id BIGINT UNSIGNED NULL, ADD COLUMN delivery_fee_cents INT NOT NULL DEFAULT 0, ADD COLUMN delivery_payout_cents INT NOT NULL DEFAULT 0, ADD CONSTRAINT fk_carts_delivery_zone FOREIGN KEY(delivery_zone_id) REFERENCES delivery_zones(id) ON DELETE SET NULL",
        "ALTER TABLE orders ADD COLUMN delivery_zone_name VARCHAR(191) NULL, ADD COLUMN delivery_payout_cents INT NOT NULL DEFAULT 0",
    ] as $sql) $db->execute($sql);
    $db->execute("INSERT INTO permissions(permission_key,label) SELECT 'deliveries.manage','deliveries.manage' WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE permission_key='deliveries.manage')");
    $db->execute("INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.permission_key='deliveries.manage' WHERE r.name='owner' AND NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=r.id AND rp.permission_id=p.id)");
    $db->execute("INSERT INTO business_settings(business_id,setting_key,setting_value) SELECT b.id,'delivery.pin_key',SHA2(CONCAT(b.id,RAND(),UUID()),256) FROM businesses b WHERE NOT EXISTS (SELECT 1 FROM business_settings bs WHERE bs.business_id=b.id AND bs.setting_key='delivery.pin_key')");
};
